name: Update translations
on:
  workflow_dispatch:
  push:
    paths:
    - 'EduID/localizations.yaml'
jobs:
  sync-myconext:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '#AUTO#') }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
      - name: Get token for myconext repo
        uses: actions/create-github-app-token@v1
        id: app-token-myconext
        with:
          app-id: ${{ secrets.SYNC_APP_ID }}
          private-key: ${{ secrets.SYNC_PRIVATE_KEY }}
          owner: OpenConext
      - name: Create PR for new translation in Openconext-myconext
        uses: BetaHuhn/repo-file-sync-action@v1
        with:
          GH_INSTALLATION_TOKEN: ${{ steps.app-token-myconext.outputs.token }}
          COMMIT_PREFIX: "#AUTO#"
          CONFIG_PATH: .github/sync-myconext.yml
  sync-eduid-app-android:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '#AUTO#') }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
      - name: Get token for eduid-app-android repo
        uses: actions/create-github-app-token@v1
        id: app-token-eduid-app-android
        with:
          app-id: ${{ secrets.SYNC_APP_ID }}
          private-key: ${{ secrets.SYNC_PRIVATE_KEY }}
          owner: Tiqr
      - name: Create PR for new translation in eduid-app-android
        uses: BetaHuhn/repo-file-sync-action@v1
        with:
          GH_INSTALLATION_TOKEN: ${{ steps.app-token-eduid-app-android.outputs.token }}
          COMMIT_PREFIX: "#AUTO#"
          CONFIG_PATH: .github/sync-eduid-app-android.yml
  localicious:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
        cache-dependency-path: 'EduID/'
    - name: Install localicious/
      run: |
        npm install -g @picnicsupermarket/localicious
    - name: Create Localizable.strings files
      run: |
        cd ${{ github.workspace }}
        localicious render EduID/localizations.yaml EduID/ --languages en,nl --outputTypes ios -c SHARED
    - name: Move files and clean up
      run: |
        cd ${{ github.workspace }}
        mv EduID/ios/en/Localizable.strings EduID/Resources/General/en.lproj/Localizable.strings
        mv EduID/ios/nl/Localizable.strings EduID/Resources/General/nl.lproj/Localizable.strings
        mv EduID/ios/Localizable.swift EduID/Localizable.swift
        rm -rf ios
    - name: Commit updated files
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Automated update of Localizable.strings after updating localizations.yaml
        file_pattern: '**/Localizable.strings **/Localizable.swift'

  